#!/usr/bin/perl -w

# Generate usys.S, the CPUTwo syscall stubs.
# CPUTwo ABI: r0 = syscall number, r1-r3 = args, r0 = return value.
# The SYSCALL instruction traps into the kernel.

print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
        print ".global $prefix$name\n";
        print "$prefix$name:\n";
    } else {
        print ".global $name\n";
        print "$name:\n";
    }
    # Load syscall number into r0, then issue SYSCALL.
    # Arguments are already in r1-r3 per the C calling convention
    # (CPUTwo ABI: first arg in r0, but we shift: the caller puts args
    # in r0-r2, we save r0 to r1 and put number in r0).
    # Actually: C ABI passes args in r0-r3.  For syscalls, we need the
    # syscall number in r0.  The simplest stub: save the first arg (r0)
    # into r1 before overwriting r0 with the syscall number.
    # BUT: many syscalls have 0-3 args already in r0-r2.  We need to
    # shift them all up by one slot (r0→r1, r1→r2, r2→r3) to make room
    # for the syscall number.
    #
    # Shift args: r3=r2, r2=r1, r1=r0, r0=SYS_name.
    # Hardware preserves all GPRs (including lr) across trap entry,
    # so no need to save/restore lr around SYSCALL.
    print " mov r3, r2\n";
    print " mov r2, r1\n";
    print " mov r1, r0\n";
    print " movi r0, SYS_${name}\n";
    print " syscall\n";
    print " mov r15, r14\n";   # ret
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
